#!/bin/sh -e
VERSION="$1"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. '1.0.0')"
    exit 1
fi

echo "Updating package.json version"
sed -E -i "" "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$VERSION\"/g" package.json
git add package.json
git commit -m "Version $VERSION"
git tag -a "v$VERSION" -m "v$VERSION"

echo "Publishing to npm"
npm run build
npm publish --access public

git push && git push --tags
