name: nextrelease
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, edited, synchronize]

jobs:
  sync:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' && github.head_ref == 'nextrelease' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # all branches and tags
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: dropseed/nextrelease@v1
      env:
        NODE_AUTH_TOKEN: ${{ secrets.DROPSEED_NPM_TOKEN }}
      with:
        prepare_cmd: |
          npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
        publish_cmd: |
          npm ci
          npm run build
          npm publish --access public
        github_token: ${{ secrets.GITHUB_TOKEN }}
